let suggestions = ["Kiwi Ice Cream",
"Murg Zafrani Tikka",
"Nutty Cookies",
"Quinoa Upma",
"Kakori Kebab Zaitooni",
"Kachumber Salad",
"Green Chilli Fry",
"Moroccan Meatballs",
"Grilled Lobster Rolls with Apple and Cabbage Slaw",
"Berry Chia Jar",
"Beer Batter Fish Fingers",
"Chicken Pakora",
"Mango Shrikhand",
"Hasselback Potatoes",
"Jain Samosa",
"Broccoli Spinach Cheela",
"Chikoo Popsicle",
"Cheese Rakakat",
"Creamy Corn Chaat",
"Caramel Pancake",
"Chilli Garlic Wedges",
"Egg Chilli Dry",
"Oatmeal Balls",
"Tandoori Chicken Sandwich",
"Pancake Cereal",
"Oats Mini Uttapam",
"Rajasthani Lapsi",
"Keto Lemon Chicken",
"Watermelon Pizza",
"Fruity Mango Smoothie Bowl",
"Beetroot Aloo Cutlet",
"Gamjajeon",
"Coconut Jaggery Poha",
"Olive Corn Pizza",
"Weightloss Coffee",
"Souffle Omelette",
"Peri Peri Shrimps",
"Blueberry Coffee Smoothie",
"Chickpea Tofu",
"Banana Pancakes"
];